server:
  port: 8081
  servlet:
    context-path: /spring-boot-homework
    jsp:
      init-parameters:
        development:  true  #开始jsp的热部署
#数据源的配置
spring:
  datasource:
    username: root
    password: 1234
    url:  jdbc:mysql://192.168.64.199:8066/test_schema
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp   #配置视图解析器
    date-format: yyyy-MM-dd #设置接受参数的时间格式类型
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd #设置页面传递的时间格式类型
#mybatis的配置 配置mybatis的mapper文件的位置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml